version: "3.8"
services:
  ignite:
    image: damintsew/shared-index-server:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - BASE-URL=http://localhost:8125/shared-index
    container_name: web-server
    ports:
      - "8125:8125"
    volumes:
      - "../../data:/var/data:"